### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Obote** [Amrhub/myPortfolio#6]
### Hello @Amrhub :smile: 
Your effort in this project is highly commendable 👏

- Linter checks (HTML+CSS) is running with no errors 💯
- PR title and summary looks professional 👍

Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it 😊

### Required Changes ♻️

- It would be nice if you add actual images in the image placeholder

**Comment by Amrhub** [comment]
Thanks, @Obote  :smile: 
Highly appreciate your feedback!
The issue was taking into consideration and has been solved
